### ISSUE TITLE
是否有相關的配置文件說明？

### ISSUE THREAD

**Issue by yatounoneko** [wy580477/sing-warp#1]
抱歉，我在配置文件那邊看得一頭霧水，那個sing-box配置里的tag是否和warp有關係？

另外想問下`/opt/sing-warp/proxy_config`中的配置是否和sing-box有直接關係？
修改`/opt/sing-warp/proxy_config`會不會覆蓋`/opt/sing-warp/config.json`？
還是只需要配置`/opt/sing-warp/config.json`即可？

**Comment by wy580477** [comment]
1. 不知道你说的是哪个 tag

2. /opt/sing-warp/proxy_config  是入站配置，提供 socks 和 vmess 入站协议配置

3. 会覆盖 /opt/sing-warp/config.json 里面相关项目

4. 我是考虑很多人不会改 json 文件，所以做了这个。会写 json 的话，自己改改也行。

**Comment by yatounoneko** [comment]
瞭解了，tag是singbox的配置文件里的，翻了下singbox的說明，現在懂了。
主要是不知道怎麼配置outgoing和warp，感謝🙏
